### ISSUE TITLE
Jekyll 3.1.1 doesn't support GFM fenced codeblocks

### ISSUE THREAD

**Issue by twouters** [udevbe/udevbe.github.io#3]
Jekyll 3.1.1 doesn't highlight backtick style fenced codeblocks, e.g.

    ```ruby
    def print_hi(name)
         puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    ```
See https://github.com/jekyll/jekyll/issues/4427 for more details

Current workaround is to use Jekyll 3.0.3 - `gem install jekyll -v 3.0.3`

**Comment by dylankb** [comment]
This fixed my issue. Thanks!

**Comment by twouters** [comment]
3.1.2 is released with a fix
